import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { Sparkles, Dumbbell } from "lucide-react";
import { useProfile } from "@/hooks/use-profile";
import { generateWorkoutPlan } from "@/lib/ai/coach.functions";
import type { WorkoutPlan } from "@/lib/ai/schemas";
import { ErrorState, LoadingState } from "@/components/States";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/ai-workout/")({
  head: () => ({ meta: [{ title: "AI Workout Planner — GymSathi" }] }),
  component: Page,
});

function Page() {
  const { profile, loading, user } = useProfile();
  const gen = useServerFn(generateWorkoutPlan);
  const [busy, setBusy] = useState(false);
  const [plan, setPlan] = useState<WorkoutPlan | null>(null);
  const [source, setSource] = useState<"ai" | "mock" | null>(null);
  const [err, setErr] = useState<string | null>(null);

  if (loading) return <LoadingState rows={3} />;
  if (!user) return <Redirect msg="Sign in to use the AI workout planner." to="/profile" cta="Sign in" />;
  if (!profile) return <Redirect msg="Set up your profile first." to="/onboarding" cta="Start onboarding" />;

  const run = async () => {
    setBusy(true); setErr(null);
    try {
      const res = await gen({ data: profile });
      setPlan(res.plan); setSource(res.source);
      await supabase.from("ai_workout_plans").insert({ user_id: user.id, name: res.plan.name, plan: res.plan as any });
      toast.success(res.source === "ai" ? "AI workout plan ready!" : "Generated using demo data");
    } catch (e: any) {
      setErr(e?.message || "Failed to generate plan");
    } finally { setBusy(false); }
  };

  return (
    <div className="space-y-6">
      <header>
        <span className="inline-flex items-center gap-1.5 rounded-full bg-accent px-3 py-1 text-xs font-semibold text-accent-foreground">
          <Sparkles className="h-3.5 w-3.5" /> AI Workout
        </span>
        <h1 className="mt-2 font-display text-3xl font-bold">Your personalized workout</h1>
        <p className="text-sm text-muted-foreground">Built around your gym access, experience and limitations.</p>
      </header>

      {!plan && (
        <div className="rounded-3xl border border-dashed border-border bg-card/50 p-8 text-center">
          <Dumbbell className="mx-auto h-10 w-10 text-muted-foreground" />
          <p className="mt-3 text-sm text-muted-foreground">Build a multi-day plan with sets, reps, form tips and rest times.</p>
          <button onClick={run} disabled={busy} className="mt-4 rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">
            {busy ? "Generating…" : "Generate my workout plan"}
          </button>
        </div>
      )}

      {err && <ErrorState message={err} onRetry={run} />}

      {plan && (
        <>
          <div className="rounded-2xl border border-border bg-card p-5">
            <div className="font-display text-xl font-bold">{plan.name}</div>
            <p className="mt-1 text-sm text-muted-foreground">{plan.summary}</p>
            <div className="mt-3 flex flex-wrap gap-2 text-xs">
              <span className="rounded-full bg-accent px-2 py-1 text-accent-foreground">{source === "ai" ? "Generated by AI" : "Demo plan"}</span>
              <button onClick={run} disabled={busy} className="rounded-full border border-border px-2 py-1 hover:bg-secondary">{busy ? "…" : "Regenerate"}</button>
            </div>
          </div>

          <section className="space-y-3">
            {plan.days.map((d, i) => (
              <div key={i} className="overflow-hidden rounded-2xl border border-border bg-card">
                <div className="flex items-center justify-between border-b border-border px-4 py-3">
                  <div>
                    <div className="font-semibold">{d.day} · {d.focus}</div>
                    <div className="text-xs text-muted-foreground">~{d.durationMin} min</div>
                  </div>
                </div>
                <div className="divide-y divide-border">
                  {d.exercises.map((ex, j) => (
                    <div key={j} className="px-4 py-3">
                      <div className="flex items-baseline justify-between gap-2">
                        <div className="font-semibold">{ex.name}</div>
                        <div className="text-xs text-muted-foreground">{ex.sets} × {ex.reps} · {ex.rest}</div>
                      </div>
                      <div className="text-xs text-muted-foreground">{ex.muscle} · {ex.difficulty}</div>
                      <div className="mt-1 text-xs"><span className="font-semibold">Form:</span> {ex.formTip}</div>
                      <div className="text-xs text-destructive/80"><span className="font-semibold">Avoid:</span> {ex.commonMistake}</div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </section>

          <p className="text-center text-xs text-muted-foreground">General fitness guidance only. Stop and consult a professional if you feel pain.</p>
        </>
      )}
    </div>
  );
}

function Redirect({ msg, to, cta }: { msg: string; to: "/profile" | "/onboarding"; cta: string }) {
  return (
    <div className="mx-auto max-w-md rounded-2xl border border-border bg-card p-6 text-center">
      <p className="text-sm text-muted-foreground">{msg}</p>
      <Link to={to} className="mt-3 inline-block rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">{cta}</Link>
    </div>
  );
}
