/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeeklyPlannerIndexRouteImport } from './routes/weekly-planner/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingChatIndexRouteImport } from './routes/onboarding-chat/index'
import { Route as MealPrepCalendarIndexRouteImport } from './routes/meal-prep-calendar/index'
import { Route as MealPlansIndexRouteImport } from './routes/meal-plans/index'
import { Route as GroceryListIndexRouteImport } from './routes/grocery-list/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as CalculatorIndexRouteImport } from './routes/calculator/index'
import { Route as AiWorkoutIndexRouteImport } from './routes/ai-workout/index'
import { Route as AiMealIndexRouteImport } from './routes/ai-meal/index'
import { Route as ExercisesIdRouteImport } from './routes/exercises/$id'
import { Route as AdminTestersRouteImport } from './routes/admin/testers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyPlannerIndexRoute = WeeklyPlannerIndexRouteImport.update({
  id: '/weekly-planner/',
  path: '/weekly-planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingChatIndexRoute = OnboardingChatIndexRouteImport.update({
  id: '/onboarding-chat/',
  path: '/onboarding-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPrepCalendarIndexRoute = MealPrepCalendarIndexRouteImport.update({
  id: '/meal-prep-calendar/',
  path: '/meal-prep-calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlansIndexRoute = MealPlansIndexRouteImport.update({
  id: '/meal-plans/',
  path: '/meal-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListIndexRoute = GroceryListIndexRouteImport.update({
  id: '/grocery-list/',
  path: '/grocery-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkoutIndexRoute = AiWorkoutIndexRouteImport.update({
  id: '/ai-workout/',
  path: '/ai-workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMealIndexRoute = AiMealIndexRouteImport.update({
  id: '/ai-meal/',
  path: '/ai-meal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/exercises/$id',
  path: '/exercises/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestersRoute = AdminTestersRouteImport.update({
  id: '/admin/testers',
  path: '/admin/testers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/testers': typeof AdminTestersRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/ai-meal/': typeof AiMealIndexRoute
  '/ai-workout/': typeof AiWorkoutIndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/grocery-list/': typeof GroceryListIndexRoute
  '/meal-plans/': typeof MealPlansIndexRoute
  '/meal-prep-calendar/': typeof MealPrepCalendarIndexRoute
  '/onboarding-chat/': typeof OnboardingChatIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/weekly-planner/': typeof WeeklyPlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/testers': typeof AdminTestersRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/ai-meal': typeof AiMealIndexRoute
  '/ai-workout': typeof AiWorkoutIndexRoute
  '/calculator': typeof CalculatorIndexRoute
  '/coach': typeof CoachIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/grocery-list': typeof GroceryListIndexRoute
  '/meal-plans': typeof MealPlansIndexRoute
  '/meal-prep-calendar': typeof MealPrepCalendarIndexRoute
  '/onboarding-chat': typeof OnboardingChatIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/plans': typeof PlansIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/weekly-planner': typeof WeeklyPlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/testers': typeof AdminTestersRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/ai-meal/': typeof AiMealIndexRoute
  '/ai-workout/': typeof AiWorkoutIndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/grocery-list/': typeof GroceryListIndexRoute
  '/meal-plans/': typeof MealPlansIndexRoute
  '/meal-prep-calendar/': typeof MealPrepCalendarIndexRoute
  '/onboarding-chat/': typeof OnboardingChatIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/weekly-planner/': typeof WeeklyPlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/testers'
    | '/exercises/$id'
    | '/ai-meal/'
    | '/ai-workout/'
    | '/calculator/'
    | '/coach/'
    | '/exercises/'
    | '/favorites/'
    | '/grocery-list/'
    | '/meal-plans/'
    | '/meal-prep-calendar/'
    | '/onboarding-chat/'
    | '/onboarding/'
    | '/plans/'
    | '/profile/'
    | '/progress/'
    | '/recipes/'
    | '/weekly-planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/testers'
    | '/exercises/$id'
    | '/ai-meal'
    | '/ai-workout'
    | '/calculator'
    | '/coach'
    | '/exercises'
    | '/favorites'
    | '/grocery-list'
    | '/meal-plans'
    | '/meal-prep-calendar'
    | '/onboarding-chat'
    | '/onboarding'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/weekly-planner'
  id:
    | '__root__'
    | '/'
    | '/admin/testers'
    | '/exercises/$id'
    | '/ai-meal/'
    | '/ai-workout/'
    | '/calculator/'
    | '/coach/'
    | '/exercises/'
    | '/favorites/'
    | '/grocery-list/'
    | '/meal-plans/'
    | '/meal-prep-calendar/'
    | '/onboarding-chat/'
    | '/onboarding/'
    | '/plans/'
    | '/profile/'
    | '/progress/'
    | '/recipes/'
    | '/weekly-planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminTestersRoute: typeof AdminTestersRoute
  ExercisesIdRoute: typeof ExercisesIdRoute
  AiMealIndexRoute: typeof AiMealIndexRoute
  AiWorkoutIndexRoute: typeof AiWorkoutIndexRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  GroceryListIndexRoute: typeof GroceryListIndexRoute
  MealPlansIndexRoute: typeof MealPlansIndexRoute
  MealPrepCalendarIndexRoute: typeof MealPrepCalendarIndexRoute
  OnboardingChatIndexRoute: typeof OnboardingChatIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  WeeklyPlannerIndexRoute: typeof WeeklyPlannerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-planner/': {
      id: '/weekly-planner/'
      path: '/weekly-planner'
      fullPath: '/weekly-planner/'
      preLoaderRoute: typeof WeeklyPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-chat/': {
      id: '/onboarding-chat/'
      path: '/onboarding-chat'
      fullPath: '/onboarding-chat/'
      preLoaderRoute: typeof OnboardingChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-prep-calendar/': {
      id: '/meal-prep-calendar/'
      path: '/meal-prep-calendar'
      fullPath: '/meal-prep-calendar/'
      preLoaderRoute: typeof MealPrepCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plans/': {
      id: '/meal-plans/'
      path: '/meal-plans'
      fullPath: '/meal-plans/'
      preLoaderRoute: typeof MealPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-list/': {
      id: '/grocery-list/'
      path: '/grocery-list'
      fullPath: '/grocery-list/'
      preLoaderRoute: typeof GroceryListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workout/': {
      id: '/ai-workout/'
      path: '/ai-workout'
      fullPath: '/ai-workout/'
      preLoaderRoute: typeof AiWorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-meal/': {
      id: '/ai-meal/'
      path: '/ai-meal'
      fullPath: '/ai-meal/'
      preLoaderRoute: typeof AiMealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/exercises/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testers': {
      id: '/admin/testers'
      path: '/admin/testers'
      fullPath: '/admin/testers'
      preLoaderRoute: typeof AdminTestersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminTestersRoute: AdminTestersRoute,
  ExercisesIdRoute: ExercisesIdRoute,
  AiMealIndexRoute: AiMealIndexRoute,
  AiWorkoutIndexRoute: AiWorkoutIndexRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  GroceryListIndexRoute: GroceryListIndexRoute,
  MealPlansIndexRoute: MealPlansIndexRoute,
  MealPrepCalendarIndexRoute: MealPrepCalendarIndexRoute,
  OnboardingChatIndexRoute: OnboardingChatIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  WeeklyPlannerIndexRoute: WeeklyPlannerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
