
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS dob date,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS dairy_ok boolean,
  ADD COLUMN IF NOT EXISTS eggs_ok boolean,
  ADD COLUMN IF NOT EXISTS spice_level text,
  ADD COLUMN IF NOT EXISTS sweet_cravings_pref text,
  ADD COLUMN IF NOT EXISTS preferred_cuisines text[],
  ADD COLUMN IF NOT EXISTS meal_prep_windows text,
  ADD COLUMN IF NOT EXISTS work_days text[],
  ADD COLUMN IF NOT EXISTS work_time_start text,
  ADD COLUMN IF NOT EXISTS work_time_end text,
  ADD COLUMN IF NOT EXISTS commute_min integer,
  ADD COLUMN IF NOT EXISTS free_time text,
  ADD COLUMN IF NOT EXISTS workout_time_pref text,
  ADD COLUMN IF NOT EXISTS reminders_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS reminder_start text,
  ADD COLUMN IF NOT EXISTS reminder_end text,
  ADD COLUMN IF NOT EXISTS reminder_interval_min integer,
  ADD COLUMN IF NOT EXISTS morning_exercise boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS afternoon_exercise boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS home_exercise_min integer,
  ADD COLUMN IF NOT EXISTS equipment text[];
